package com.example.cars.service;

import com.example.cars.model.Car;
import com.example.cars.repository.CarRepository;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.Optional;

@Service
public class CarService {

    private final CarRepository carRepository;

    // Inject CarRepository via constructor
    public CarService(CarRepository carRepository) {
        this.carRepository = carRepository;
    }

    // Retrieve all cars from the database
    public List<Car> getAllCars() {
        return carRepository.findAll();
    }

    // Retrieve a car by ID
    public Optional<Car> getCarById(Long id) {
        return carRepository.findById(id);
    }

    // Add a new car
    public Car addCar(Car newCar) {
        // The ID will be automatically generated by the database
        return carRepository.save(newCar);
    }

    // Update an existing car
    public Optional<Car> updateCar(Long id, Car updatedCar) {
        if (carRepository.existsById(id)) {
            updatedCar.setId(id); // Set the ID for the updated car
            return Optional.of(carRepository.save(updatedCar)); // Save and return updated car
        }
        return Optional.empty(); // Car not found
    }

    // Delete a car by ID
    public boolean deleteCar(Long id) {
        if (carRepository.existsById(id)) {
            carRepository.deleteById(id);
            return true; // Car deleted
        }
        return false; // Car not found
    }
}
